/**
 * KDP Pre-Upload Checklist Generator
 * Generates a text checklist explaining KDP requirements
 */

/**
 * Book data for checklist generation
 */
export interface BookData {
  title: string
  author?: string
  trimSize: string
  paperType: string
  pageCount: number
  interiorWidth: number
  interiorHeight: number
  coverWidth: number
  coverHeight: number
  spineWidth: number
}

/**
 * Generate KDP pre-upload checklist text
 * @param book - Book data
 * @returns Plain text checklist content
 */
export function generateChecklist(book: BookData): string {
  const lines: string[] = []
  
  // Header
  lines.push('=' .repeat(60))
  lines.push('KDP PRE-UPLOAD CHECKLIST')
  lines.push('=' .repeat(60))
  lines.push('')
  
  // Book Info
  lines.push('BOOK INFORMATION')
  lines.push('-'.repeat(40))
  lines.push(`Title: ${book.title}`)
  if (book.author) {
    lines.push(`Author: ${book.author}`)
  }
  lines.push(`Trim Size: ${book.trimSize}`)
  lines.push(`Paper Type: ${formatPaperType(book.paperType)}`)
  lines.push(`Page Count: ${book.pageCount} pages`)
  lines.push('')
  
  // Interior File Specifications
  lines.push('INTERIOR FILE SPECIFICATIONS')
  lines.push('-'.repeat(40))
  lines.push(`File: interior.pdf`)
  lines.push(`Dimensions: ${book.interiorWidth}" x ${book.interiorHeight}"`)
  lines.push(`Trim Size: ${book.trimSize}`)
  lines.push(`Margins: KDP recommended (0.5" inside, 0.75" outside/bottom)`)
  lines.push(`Font Embedding: All fonts embedded in PDF`)
  lines.push('')
  
  // Cover File Specifications
  lines.push('COVER FILE SPECIFICATIONS')
  lines.push('-'.repeat(40))
  lines.push(`File: cover.pdf`)
  lines.push(`Dimensions: ${book.coverWidth}" x ${book.coverHeight}" (with bleed)`)
  lines.push(`Spine Width: ${book.spineWidth.toFixed(3)}"`)
  lines.push(`Bleed: 0.125" on all sides`)
  lines.push(`Image Resolution: 300 DPI minimum (600 DPI recommended)`)
  lines.push(`Color Mode: CMYK for color, Grayscale for B&W`)
  lines.push('')
  
  // KDP Upload Requirements
  lines.push('KDP UPLOAD REQUIREMENTS')
  lines.push('-'.repeat(40))
  lines.push('- File Format: PDF only')
  lines.push('- Maximum File Size: 650MB')
  lines.push('- PDF/X-1a:2001 recommended for best compatibility')
  lines.push('- ISBN will be assigned by KDP (or use your own)')
  lines.push('')
  
  // Pre-Upload Verification Steps
  lines.push('PRE-UPLOAD VERIFICATION STEPS')
  lines.push('-'.repeat(40))
  lines.push('1. Verify interior PDF opens correctly in PDF reader')
  lines.push('2. Check all text is visible and not cut off by margins')
  lines.push('3. Verify images are clear (not pixelated)')
  lines.push('4. Confirm cover spine width matches your book specifications')
  lines.push('5. Check that front and back covers align properly')
  lines.push('6. Verify page numbers are sequential and correct')
  lines.push('7. Review table of contents links work correctly')
  lines.push('')
  
  // Publishing Steps
  lines.push('NEXT STEPS TO PUBLISH')
  lines.push('-'.repeat(40))
  lines.push('1. Go to kdp.amazon.com and sign in')
  lines.push('2. Click "Create Kindle eBook" or "Create Paperback"')
  lines.push('3. Upload interior.pdf to Manuscript section')
  lines.push('4. Upload cover.pdf to Cover section')
  lines.push('5. Fill in book details (title, description, categories)')
  lines.push('6. Set your pricing and royalty options')
  lines.push('7. Click "Publish Your Book"')
  lines.push('')
  
  // Notes
  lines.push('NOTES')
  lines.push('-'.repeat(40))
  lines.push('- KDP typically approves books within 24-72 hours')
  lines.push('- You can make changes after publication')
  lines.push('- Use KDP Cover Creator for simple covers')
  lines.push('- Contact KDP support for complex issues')
  lines.push('')
  
  // Footer
  lines.push('=' .repeat(60))
  lines.push(`Generated by Publik on ${new Date().toLocaleDateString()}`)
  lines.push('=' .repeat(60))
  
  return lines.join('\n')
}

/**
 * Format paper type for display
 */
function formatPaperType(paperType: string): string {
  const typeMap: Record<string, string> = {
    'white': 'White',
    'cream': 'Cream',
    'standard-color': 'Standard Color',
    'premium-color': 'Premium Color'
  }
  return typeMap[paperType] || paperType
}

/**
 * Get checklist filename for a book
 */
export function getChecklistFilename(bookTitle: string): string {
  const sanitized = bookTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
  return `${sanitized}-kdp-checklist.txt`
}
