import { PublishingGuide } from "@/components/export/PublishingGuide"

export const metadata = {
  title: "Publishing Your Book on Amazon KDP - Publik",
  description: "Step-by-step guide to uploading and publishing your book on Amazon KDP using files generated by Publik.",
}

/**
 * Publishing Guide Page
 * Standalone page with step-by-step KDP publishing instructions
 */
export default function PublishingGuidePage() {
  return (
    <div className="max-w-5xl mx-auto p-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">
          Publishing Your Book on Amazon KDP
        </h1>
        <p className="text-gray-600 mt-3 text-lg">
          Follow these steps to upload and publish your book using the KDP-ready files 
          you generated with Publik. This guide walks you through the entire publishing process.
        </p>
      </div>
      
      {/* Introduction */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
        <h2 className="font-semibold text-blue-900 mb-2">Before You Begin</h2>
        <ul className="list-disc list-inside text-blue-800 space-y-1">
          <li>Download your ZIP package from the export page</li>
          <li>Extract the files: interior.pdf, cover.pdf, and kdp-checklist.txt</li>
          <li>Have your book description, keywords, and categories ready</li>
          <li>Decide on your pricing strategy</li>
        </ul>
      </div>
      
      {/* Guide Content */}
      <PublishingGuide showSidebar={true} />
      
      {/* Bottom Note */}
      <div className="mt-12 pt-8 border-t">
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="font-semibold text-green-900 mb-2">After Publication</h3>
          <p className="text-green-800">
            Once you publish, your book will typically be available on Amazon within 24-72 hours 
            after KDP review. You can make changes to your book details anytime through your KDP dashboard.
          </p>
        </div>
      </div>
    </div>
  )
}
